name: portabase-agent-b

services:

  app:
    image: ${AGENT_IMAGE:-portabase/agent:latest}
    mem_limit: 256m
    cpus: 0.2
    restart: unless-stopped
    volumes:
      - ./databases.toml:/config/config.toml
      - sqlite-3.46-data:/sqlite-3.46
      - sqlite-3.45-data:/sqlite-3.45
    environment:
      LOG: info
      TZ: "UTC"
      POLLING: 5
      EDGE_KEY: "${EDGE_KEY}"
      DATABASES_CONFIG_FILE: "config.toml"
    networks:
      - portabase
    extra_hosts:
      - "localhost:host-gateway"

networks:
  portabase:
    name: portabase
    external: true

volumes:
  sqlite-3.46-data:
    external: true
    name: database_sqlite-3.46-backup-e2e-data
  sqlite-3.45-data:
    external: true
    name: database_sqlite-3.45-backup-e2e-data
